services:
  mongodb:
    image: mongo:latest
    
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - "mongodb:/data/db"
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    
    restart: always

  postgresdb:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mini_rag_app
    volumes:
      - pgdata:/var/lib/postgresql/data
      
networks:
  backend:

volumes:
  mongodb:
  pgdata:
