services:
  mongodb:
    image: mongo:latest
    
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - "mongodb:/data/db"
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    
    restart: always

  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    restart: always
      
networks:
  backend:

volumes:
  mongodb:
  pgdata:
